/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author AhmadGuntur
 */
public class Cinema25 extends javax.swing.JFrame {

    film flm = new film();

    /**
     * Creates new form Cinema25
     */
    public Cinema25() {
        initComponents();
        jenisfilm.addItem("PILIH");
        jenisfilm.addItem("Doctor Strange : Multiverse of Darkness");
        jenisfilm.addItem("Shang-Chi and the Legend of the Ten Rings");

        jamtayang.addItem("PILIH");
        jamtayang.addItem("11.05");
        jamtayang.addItem("19.05");

        nonaktif();
        bersih();
    }

    void bersih() {
        jenisfilm.setSelectedItem("PILIH");
        jamtayang.setSelectedItem("PILIH");
        lharga.setText("");
        ljbeli.setText("");
        ltharga.setText("");
        lub.setText("");
        luk.setText("");
    }

    void aktif() {
        jenisfilm.setEnabled(true);
        jamtayang.setEnabled(true);
        ljbeli.setEnabled(true);
        lub.setEnabled(true);
    }

    void nonaktif() {
        jenisfilm.setEnabled(false);
        jamtayang.setEnabled(false);
        lharga.setEnabled(false);
        ljbeli.setEnabled(false);
        ltharga.setEnabled(false);
        lub.setEnabled(false);
        luk.setEnabled(false);
    }

    void tersedia() {
        if (jenisfilm.getSelectedItem() == null || jamtayang.getSelectedItem() == null) {
        return;
        }
        l1.setBackground(Color.LIGHT_GRAY);
        l2.setBackground(Color.LIGHT_GRAY);
        l3.setBackground(Color.LIGHT_GRAY);
        l4.setBackground(Color.LIGHT_GRAY);
        ml1.setBackground(Color.LIGHT_GRAY);
        ml2.setBackground(Color.LIGHT_GRAY);
        ml3.setBackground(Color.LIGHT_GRAY);
        m1.setBackground(Color.LIGHT_GRAY);
        m2.setBackground(Color.LIGHT_GRAY);
        m3.setBackground(Color.LIGHT_GRAY);
        mr1.setBackground(Color.LIGHT_GRAY);
        mr2.setBackground(Color.LIGHT_GRAY);
        mr3.setBackground(Color.LIGHT_GRAY);
        r1.setBackground(Color.LIGHT_GRAY);
        r2.setBackground(Color.LIGHT_GRAY);
        r3.setBackground(Color.LIGHT_GRAY);
        r4.setBackground(Color.LIGHT_GRAY);
        
        String pilihanFilm = jenisfilm.getSelectedItem().toString();
        String pilihanJam = jamtayang.getSelectedItem().toString();
        if (pilihanFilm.equals("PILIH") || pilihanJam.equals("PILIH")) {
        return;
        }
        l1.setBackground(Color.GREEN);
        l2.setBackground(Color.GREEN);
        l3.setBackground(Color.GREEN);
        l4.setBackground(Color.GREEN);
        ml1.setBackground(Color.GREEN);
        ml2.setBackground(Color.GREEN);
        ml3.setBackground(Color.GREEN);
        m1.setBackground(Color.GREEN);
        m2.setBackground(Color.GREEN);
        m3.setBackground(Color.GREEN);
        mr1.setBackground(Color.GREEN);
        mr2.setBackground(Color.GREEN);
        mr3.setBackground(Color.GREEN);
        r1.setBackground(Color.GREEN);
        r2.setBackground(Color.GREEN);
        r3.setBackground(Color.GREEN);
        r4.setBackground(Color.GREEN);
    }
    
    void terisi(){
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        title = new javax.swing.JTextField();
        bclear = new javax.swing.JButton();
        bbeli = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        Judul = new javax.swing.JLabel();
        jenisfilm = new javax.swing.JComboBox<>();
        Jamtayang = new javax.swing.JLabel();
        jamtayang = new javax.swing.JComboBox<>();
        Harga = new javax.swing.JLabel();
        lharga = new javax.swing.JTextField();
        Jumlahbeli = new javax.swing.JLabel();
        ljbeli = new javax.swing.JTextField();
        kursi = new javax.swing.JLabel();
        l1 = new javax.swing.JButton();
        l2 = new javax.swing.JButton();
        l3 = new javax.swing.JButton();
        l4 = new javax.swing.JButton();
        ml1 = new javax.swing.JButton();
        ml2 = new javax.swing.JButton();
        ml3 = new javax.swing.JButton();
        m1 = new javax.swing.JButton();
        m2 = new javax.swing.JButton();
        m3 = new javax.swing.JButton();
        mr1 = new javax.swing.JButton();
        mr2 = new javax.swing.JButton();
        mr3 = new javax.swing.JButton();
        r1 = new javax.swing.JButton();
        r2 = new javax.swing.JButton();
        r3 = new javax.swing.JButton();
        r4 = new javax.swing.JButton();
        screen = new javax.swing.JLabel();
        tembok = new javax.swing.JLabel();
        TotalHarga = new javax.swing.JLabel();
        ltharga = new javax.swing.JTextField();
        uangbayar = new javax.swing.JLabel();
        lub = new javax.swing.JTextField();
        uangkembali = new javax.swing.JLabel();
        luk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinema 25");

        base.setBackground(new java.awt.Color(37, 32, 36));
        base.setForeground(new java.awt.Color(37, 32, 36));

        title.setBackground(new java.awt.Color(37, 32, 36));
        title.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(204, 153, 0));
        title.setText("                         CINEMA XXV");
        title.setBorder(null);

        bclear.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        bclear.setText("CLEAR");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });

        bbeli.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        bbeli.setText("BELI");
        bbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbeliActionPerformed(evt);
            }
        });

        bexit.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        bexit.setText("EXIT");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        Judul.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        Judul.setForeground(new java.awt.Color(204, 153, 0));
        Judul.setText("             -JUDUL FILM-");

        jenisfilm.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jenisfilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisfilmActionPerformed(evt);
            }
        });

        Jamtayang.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        Jamtayang.setForeground(new java.awt.Color(204, 153, 0));
        Jamtayang.setText("             -JAM TAYANG-");

        jamtayang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jamtayang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jamtayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamtayangActionPerformed(evt);
            }
        });

        Harga.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        Harga.setForeground(new java.awt.Color(204, 153, 0));
        Harga.setText("Harga");

        Jumlahbeli.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        Jumlahbeli.setForeground(new java.awt.Color(204, 153, 0));
        Jumlahbeli.setText("Jumlah beli");

        ljbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ljbeliKeyPressed(evt);
            }
        });

        kursi.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        kursi.setForeground(new java.awt.Color(204, 153, 0));
        kursi.setText("                      -KURSI-");

        l1.setText("L1");
        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });

        l2.setText("L2");
        l2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2ActionPerformed(evt);
            }
        });

        l3.setText("L3");
        l3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l3ActionPerformed(evt);
            }
        });

        l4.setText("L4");
        l4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l4ActionPerformed(evt);
            }
        });

        ml1.setText("ML1");
        ml1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ml1ActionPerformed(evt);
            }
        });

        ml2.setText("ML2");
        ml2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ml2ActionPerformed(evt);
            }
        });

        ml3.setText("ML3");
        ml3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ml3ActionPerformed(evt);
            }
        });

        m1.setText("M1");
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });

        m2.setText("M2");
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });

        m3.setText("M3");
        m3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m3ActionPerformed(evt);
            }
        });

        mr1.setText("MR1");
        mr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr1ActionPerformed(evt);
            }
        });

        mr2.setText("MR2");
        mr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr2ActionPerformed(evt);
            }
        });

        mr3.setText("MR3");
        mr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr3ActionPerformed(evt);
            }
        });

        r1.setText("R1");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setText("R2");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r3.setText("R3");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        r4.setText("R4");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        screen.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        screen.setForeground(new java.awt.Color(204, 153, 0));
        screen.setText("------------------------------------------------");

        tembok.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        tembok.setForeground(new java.awt.Color(204, 153, 0));
        tembok.setText("                    |SCREEN|");

        TotalHarga.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        TotalHarga.setForeground(new java.awt.Color(204, 153, 0));
        TotalHarga.setText("Total Harga");

        uangbayar.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        uangbayar.setForeground(new java.awt.Color(204, 153, 0));
        uangbayar.setText("Uang Bayar");

        lub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lubKeyPressed(evt);
            }
        });

        uangkembali.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        uangkembali.setForeground(new java.awt.Color(204, 153, 0));
        uangkembali.setText("Uang Kembali");

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(baseLayout.createSequentialGroup()
                                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(baseLayout.createSequentialGroup()
                                        .addComponent(bbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bclear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bexit))
                                    .addGroup(baseLayout.createSequentialGroup()
                                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(uangbayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Jumlahbeli, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Harga, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(uangkembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ljbeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(lharga, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ltharga)
                                            .addComponent(lub)
                                            .addComponent(luk)))
                                    .addComponent(jenisfilm, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(baseLayout.createSequentialGroup()
                                        .addComponent(jamtayang, 0, 262, Short.MAX_VALUE)
                                        .addGap(31, 31, 31))
                                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(screen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tembok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(baseLayout.createSequentialGroup()
                                            .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(baseLayout.createSequentialGroup()
                                                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(baseLayout.createSequentialGroup()
                                                            .addComponent(l2)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(ml2)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(mr2))
                                                        .addGroup(baseLayout.createSequentialGroup()
                                                            .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(ml3)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(m3)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(mr3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(5, 5, 5))
                                                .addGroup(baseLayout.createSequentialGroup()
                                                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(baseLayout.createSequentialGroup()
                                                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(ml1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(mr1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(l4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(r4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(r3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(r2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(r1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(kursi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(33, 33, 33))
                            .addGroup(baseLayout.createSequentialGroup()
                                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(Jamtayang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(64, 64, 64)))))
                .addContainerGap())
        );

        baseLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {l2, l3, l4, m1, m2, m3, ml1, ml2, ml3, mr1, mr2, mr3, r1, r2, r3, r4});

        baseLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lharga, ljbeli, ltharga, lub, luk});

        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(Judul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenisfilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(Jamtayang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jamtayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Harga)
                            .addComponent(lharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jumlahbeli)
                            .addComponent(ljbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalHarga)
                            .addComponent(ltharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uangbayar)
                            .addComponent(lub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(luk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uangkembali))
                        .addGap(28, 28, 28)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bbeli)
                            .addComponent(bclear)
                            .addComponent(bexit)))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(kursi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l1)
                            .addComponent(m1)
                            .addComponent(ml1)
                            .addComponent(mr1)
                            .addComponent(r1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l2)
                            .addComponent(r2)
                            .addComponent(mr2)
                            .addComponent(m2)
                            .addComponent(ml2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ml3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(r3)
                                .addComponent(mr3)
                                .addComponent(m3)
                                .addComponent(l3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l4)
                            .addComponent(r4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tembok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        baseLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {l1, l2, l3, l4, m1, m2, m3, ml1, ml2, ml3, mr1, mr2, mr3, r1, r2, r3, r4});

        baseLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lharga, ljbeli, ltharga, lub, luk});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisfilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisfilmActionPerformed
        // TODO add your handling code here:
        flm.setJf(jenisfilm.getSelectedItem().toString());
        flm.listflm();
        lharga.setText(Double.toString(flm.getHrg()));
        ljbeli.requestFocus();
        tersedia();
    }//GEN-LAST:event_jenisfilmActionPerformed

    private void jamtayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamtayangActionPerformed
        // TODO add your handling code here:
        tersedia();
    }//GEN-LAST:event_jamtayangActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
        bersih();
        aktif();
    }//GEN-LAST:event_bclearActionPerformed

    private void ljbeliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ljbeliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            flm.setJml(Integer.parseInt(ljbeli.getText()));
            ltharga.setText(Double.toString(flm.getTot()));
            lub.grabFocus();
        }
    }//GEN-LAST:event_ljbeliKeyPressed

    private void lubKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lubKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            flm.setUb(Double.parseDouble(lub.getText()));
            luk.setText(Double.toString(flm.getUk()));
            if (flm.getUb() < flm.getTot()) {
                JOptionPane.showMessageDialog(null, "Pembayaran Kurang!!", "Warning", JOptionPane.OK_OPTION);
                luk.setText("");
                lub.setText("");
            } else {
                return;
            }
        }
    }//GEN-LAST:event_lubKeyPressed

    private void bbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbeliActionPerformed
        // TODO add your handling code here:
        int y;
        y = JOptionPane.showConfirmDialog(null, "Yakin beli tiket ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(y == JOptionPane.YES_OPTION){
        JOptionPane.showMessageDialog(rootPane,"Terima kasih sudah melakukan transaksi");
        bersih();
        }
        else{
            return;
        }
    }//GEN-LAST:event_bbeliActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        int x;
        x = JOptionPane.showConfirmDialog(null, "Yakin mau Keluar??", "Konfirm", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            dispose();
        } else {
            return;
        }
    }//GEN-LAST:event_bexitActionPerformed

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        l1.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_l1ActionPerformed

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        l2.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_l2ActionPerformed

    private void l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        l3.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_l3ActionPerformed

    private void l4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        l4.setBackground(Color.RED);
        }
        else{
            return;
        };
    }//GEN-LAST:event_l4ActionPerformed

    private void ml1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ml1ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        ml1.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_ml1ActionPerformed

    private void ml2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ml2ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        ml2.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_ml2ActionPerformed

    private void ml3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ml3ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        ml3.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_ml3ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        m1.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_m1ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        m2.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_m2ActionPerformed

    private void m3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m3ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        m3.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_m3ActionPerformed

    private void mr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr1ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        mr1.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_mr1ActionPerformed

    private void mr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr2ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        mr2.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_mr2ActionPerformed

    private void mr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr3ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        mr3.setBackground(Color.RED);
        }
        else{
            return;
        }
    }//GEN-LAST:event_mr3ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        r1.setBackground(Color.RED);
        }
        else{
            return;
        };
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        r2.setBackground(Color.RED);
        }
        else{
            return;
        };
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        r3.setBackground(Color.RED);
        }
        else{
            return;
        };
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        // TODO add your handling code here:
        int z;
        z = JOptionPane.showConfirmDialog(null, "Yakin pilih kursi ini?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(z == JOptionPane.YES_OPTION){
        r4.setBackground(Color.RED);
        }
        else{
            return;
        };
    }//GEN-LAST:event_r4ActionPerformed

    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cinema25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cinema25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cinema25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cinema25.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cinema25().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel Jamtayang;
    private javax.swing.JLabel Judul;
    private javax.swing.JLabel Jumlahbeli;
    private javax.swing.JLabel TotalHarga;
    private javax.swing.JPanel base;
    private javax.swing.JButton bbeli;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bexit;
    private javax.swing.JComboBox<String> jamtayang;
    private javax.swing.JComboBox<String> jenisfilm;
    private javax.swing.JLabel kursi;
    private javax.swing.JButton l1;
    private javax.swing.JButton l2;
    private javax.swing.JButton l3;
    private javax.swing.JButton l4;
    private javax.swing.JTextField lharga;
    private javax.swing.JTextField ljbeli;
    private javax.swing.JTextField ltharga;
    private javax.swing.JTextField lub;
    private javax.swing.JTextField luk;
    private javax.swing.JButton m1;
    private javax.swing.JButton m2;
    private javax.swing.JButton m3;
    private javax.swing.JButton ml1;
    private javax.swing.JButton ml2;
    private javax.swing.JButton ml3;
    private javax.swing.JButton mr1;
    private javax.swing.JButton mr2;
    private javax.swing.JButton mr3;
    private javax.swing.JButton r1;
    private javax.swing.JButton r2;
    private javax.swing.JButton r3;
    private javax.swing.JButton r4;
    private javax.swing.JLabel screen;
    private javax.swing.JLabel tembok;
    private javax.swing.JTextField title;
    private javax.swing.JLabel uangbayar;
    private javax.swing.JLabel uangkembali;
    // End of variables declaration//GEN-END:variables
}
